In [215]:
pip install pandas scikit-learn nltk

Requirement already satisfied: pandas in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (2.3.1)
Requirement already satisfied: scikit-learn in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (1.7.1)
Requirement already satisfied: nltk in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (3.9.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhia\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.3.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\abhia\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\abhia\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

#### UCI Dataset of spam and not spam (ham) messages

In [216]:
import pandas as pd 

df1 = pd.read_csv("uci", sep="\t", header=None)
df1.columns = ["label", "message"]

print(df1.head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

#### Syenthetic Dataset created by us relevent to indian fraud and phishing patterns

In [217]:
df2 = pd.read_csv("syn.csv")
df2.columns = ["label", "message"]

print(df2.head())

  label                                       message
0   ham  Don't forget to bring the documents tomorrow
1   ham  Don't forget to bring the documents tomorrow
2   ham                   Call me when you reach home
3   ham           Meeting scheduled tomorrow at 36 PM
4   ham              Happy birthday! Have a great day

In [218]:
df= pd.concat([df1, df2])
print(df)

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
4995   ham                                       Lunch at 27?
4996   ham  Your account debited Rs 843. Available balance...
4997   ham      Your OTP for login is 926436. Do not share it
4998  spam  Your SBI account suspended. Verify immediately...
4999  spam  Your parcel delivery failed. Update address ww...

[10572 rows x 2 columns]

In [219]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_message'] = df['message'].apply(clean_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abhia\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [220]:
df

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goes usf lives around though
...,...,...,...
4995,ham,Lunch at 27?,lunch 27
4996,ham,Your account debited Rs 843. Available balance...,account debited rs 843 available balance rs 14576
4997,ham,Your OTP for login is 926436. Do not share it,otp login 926436 share
4998,spam,Your SBI account suspended. Verify immediately...,sbi account suspended verify immediately wwwfl...
4999,spam,Your parcel delivery failed. Update address ww...,parcel delivery failed update address wwwflipc...

In [221]:
df = df.dropna()
df = df.reset_index(drop=True)

In [222]:
df

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goes usf lives around though
...,...,...,...
10567,ham,Lunch at 27?,lunch 27
10568,ham,Your account debited Rs 843. Available balance...,account debited rs 843 available balance rs 14576
10569,ham,Your OTP for login is 926436. Do not share it,otp login 926436 share
10570,spam,Your SBI account suspended. Verify immediately...,sbi account suspended verify immediately wwwfl...
10571,spam,Your parcel delivery failed. Update address ww...,parcel delivery failed update address wwwflipc...

## Feature Engineering

In [227]:
df['label'] = df['label'].map({'ham':0, 'spam':1})

In [228]:
from sklearn.model_selection import train_test_split

X_text = df['clean_message']
y = df['label']

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.4,
    stratify=y,
    random_state=42
)

In [229]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=900,
    ngram_range=(1,3),
    stop_words="english",
    sublinear_tf=True
)

X_train_tfidf = vectorizer.fit_transform(X_train_text)
X_test_tfidf = vectorizer.transform(X_test_text)

In [230]:
X_train_tfidf = X_train_tfidf.toarray()
X_test_tfidf = X_test_tfidf.toarray()

In [231]:
import re

def url_features(text):

    has_url = 1 if re.search(r'(http|www)', text.lower()) else 0

    suspicious_domains = ['.xyz','.top','.click','.gq','.work']
    suspicious = 1 if any(d in text.lower() for d in suspicious_domains) else 0

    shorteners = ['bit.ly','tinyurl','t.co','goo.gl']
    short = 1 if any(s in text.lower() for s in shorteners) else 0

    return [has_url, suspicious, short]

In [232]:
keywords = [
    "otp","verify","bank","account","urgent",
    "click","lottery","reward","winner","prize"
]

def keyword_features(text):

    text = text.lower()

    return [1 if k in text else 0 for k in keywords]

In [233]:
def message_stats(text):

    length = len(text) / 200

    digit_ratio = sum(c.isdigit() for c in text) / max(len(text),1)

    upper_ratio = sum(c.isupper() for c in text) / max(len(text),1)

    exclamation = 1 if "!" in text else 0

    return [length, digit_ratio, upper_ratio, exclamation]

In [234]:
import numpy as np

train_extra = []
test_extra = []

for text in X_train_text:
    train_extra.append(
        url_features(text) +
        keyword_features(text) +
        message_stats(text)
    )

for text in X_test_text:
    test_extra.append(
        url_features(text) +
        keyword_features(text) +
        message_stats(text)
    )

train_extra = np.array(train_extra)
test_extra = np.array(test_extra)

In [235]:
X_train_final = np.hstack([X_train_tfidf, train_extra])
X_test_final = np.hstack([X_test_tfidf, test_extra])

In [236]:
print(X_train_final.shape)

(6343, 917)

In [237]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train_final)
X_test = scaler.transform(X_test_final)

In [238]:
from sklearn.neural_network import MLPClassifier

ann_model = MLPClassifier(
    hidden_layer_sizes=(128, 64),   # 2 hidden layers
    activation='relu',
    solver='adam',
    max_iter=20,
    random_state=42
)
 
ann_model.fit(X_train, y_train)

c:\Users\abhia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=20, random_state=42)

#### Performance od ANN in given dataset

In [239]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

y_pred =ann_model.predict_proba(X_test)[:,1]

y_pred = (y_pred > 0.4).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-score:", f1_score(y_test, y_pred))

print("\nDetailed Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.991487349255143
Precision: 0.9809954751131221
Recall: 0.986351228389445
F1-score: 0.9836660617059891

Detailed Report:

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      3130
           1       0.98      0.99      0.98      1099

    accuracy                           0.99      4229
   macro avg       0.99      0.99      0.99      4229
weighted avg       0.99      0.99      0.99      4229

In [240]:
total_params = 0

for coef, intercept in zip(ann_model.coefs_, ann_model.intercepts_):
    total_params += coef.size      # weights
    total_params += intercept.size # bias

print("Total ANN Parameters:", total_params)

Total ANN Parameters: 125825

## Spiking Neural Networks with SnnTorch

In [241]:
pip install torch snntorch

Requirement already satisfied: torch in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (2.6.0+cu124)
Requirement already satisfied: snntorch in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (0.9.4)
Requirement already satisfied: filelock in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.14.1)
Requirement already satisfied: networkx in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (2025.9.0)
Requirement already satisfied: setuptools in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [242]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# Convert train/test data to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

# Create datasets
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [243]:
def latency_encoding(x, T=10):
    """
    x: (batch, features)
    returns: (T, batch, features)
    """
    batch_size, num_features = x.shape
    
    spike_times = (T * (1 - x)).long()   # compute spike time
    
    spikes = torch.zeros(T, batch_size, num_features)
    
    for t in range(T):
        spikes[t] = (spike_times == t).float()
        
    return spikes

In [244]:
import torch
import torch.nn as nn
import snntorch as snn
from snntorch import surrogate

beta = 0.9
spike_grad = surrogate.fast_sigmoid()

class SNNModel(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()

        self.fc1 = nn.Linear(input_size, hidden_size)
        self.lif1 = snn.Leaky(beta=beta, spike_grad=spike_grad)

        self.fc2 = nn.Linear(hidden_size, output_size)
        self.lif2 = snn.Leaky(beta=beta, spike_grad=spike_grad)

    def forward(self, x):

        mem1 = self.lif1.init_leaky()
        mem2 = self.lif2.init_leaky()

        spk2_rec = []

        num_steps = x.size(0)

        for step in range(num_steps):

            cur1 = self.fc1(x[step])
            spk1, mem1 = self.lif1(cur1, mem1)

            cur2 = self.fc2(spk1)
            spk2, mem2 = self.lif2(cur2, mem2)

            spk2_rec.append(spk2)

        return torch.stack(spk2_rec)

In [245]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

input_size = X_train.shape[1]

model = SNNModel(
    input_size=input_size,
    hidden_size=128,
    output_size=2
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

#### Model training with GPU

In [246]:
num_epochs = 12
T = 50

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    
    for data, targets in train_loader:
        data = data.to(device)
        targets = targets.to(device)
        
        spikes = latency_encoding(data, T).to(device)
        
        optimizer.zero_grad()
        
        outputs = model(spikes)
        
        # sum spikes over time
        outputs = outputs.sum(dim=0)
        
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader):.4f}")

Epoch 1, Loss: 0.6249
Epoch 2, Loss: 0.1901
Epoch 3, Loss: 0.0526
Epoch 4, Loss: 0.0304
Epoch 5, Loss: 0.0272
Epoch 6, Loss: 0.0249
Epoch 7, Loss: 0.0199
Epoch 8, Loss: 0.0189
Epoch 9, Loss: 0.0159
Epoch 10, Loss: 0.0152
Epoch 11, Loss: 0.0127
Epoch 12, Loss: 0.0123

In [247]:
from sklearn.metrics import classification_report

model.eval()
all_preds = []
all_targets = []

with torch.no_grad():
    for data, targets in test_loader:
        data = data.to(device)
        targets = targets.to(device)
        
        spikes = latency_encoding(data, T).to(device)
        outputs = model(spikes)
        outputs = outputs.sum(dim=0)
        
        preds = torch.argmax(outputs, dim=1)
        
        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(targets.cpu().numpy())

print(classification_report(all_targets, all_preds))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3130
           1       0.99      0.98      0.98      1099

    accuracy                           0.99      4229
   macro avg       0.99      0.99      0.99      4229
weighted avg       0.99      0.99      0.99      4229

#### Performance of SNN on dataset

In [248]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

model.eval()
all_preds = []
all_targets = []

with torch.no_grad():
    for data, targets in test_loader:
        data = data.to(device)
        targets = targets.to(device)

        spikes = latency_encoding(data, T).to(device)
        outputs = model(spikes)
        outputs = outputs.sum(dim=0)

        preds = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(targets.cpu().numpy())

# Convert to numpy
all_preds = np.array(all_preds)
all_targets = np.array(all_targets)

# Metrics
print("Accuracy:", accuracy_score(all_targets, all_preds))
print("Precision:", precision_score(all_targets, all_preds))
print("Recall:", recall_score(all_targets, all_preds))
print("F1-score:", f1_score(all_targets, all_preds))

print("\nDetailed Report:\n")
print(classification_report(all_targets, all_preds))

Accuracy: 0.991487349255143
Precision: 0.9853881278538813
Recall: 0.9818016378525932
F1-score: 0.98359161349134

Detailed Report:

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3130
           1       0.99      0.98      0.98      1099

    accuracy                           0.99      4229
   macro avg       0.99      0.99      0.99      4229
weighted avg       0.99      0.99      0.99      4229

In [249]:
from sklearn.metrics import roc_auc_score

roc = roc_auc_score(all_targets, all_preds)
print("ROC AUC:", roc)

from sklearn.metrics import confusion_matrix

print(confusion_matrix(all_targets, all_preds))

ROC AUC: 0.9883449083831657
[[3114   16]
 [  20 1079]]

### Most important Comparision between SNN and ANN/Traditional models

In [ ]:
import torch
import torch.nn as nn
import time
import numpy as np


ann_model.eval()
model.eval()



# INPUT DATA

input_tensor = torch.rand(1,917)



# LATENCY TEST

runs = 1000

# ANN timing
start = time.time()

for _ in range(runs):
    ann_model(input_tensor)

end = time.time()

ann_latency = (end-start)/runs


# SNN timing
start = time.time()

total_spikes = 0

for _ in range(runs):

    out, spikes = snn_model(input_tensor)
    total_spikes += spikes

end = time.time()

snn_latency = (end-start)/runs


# OPERATION COUNT

ann_ops = (917 * 128) + (128 * 2)

# SNN operations depend on spikes
avg_spikes = total_spikes / runs

snn_ops = avg_spikes



# Typical neuromorphic estimates

MAC_energy = 3.2e-12
AC_energy = 0.1e-12

ann_energy = ann_ops * MAC_energy
snn_energy = snn_ops * AC_energy


# RESULTS

print("\n===== ANN vs SNN Comparison =====\n")

print("ANN Operations:", ann_ops)
print("SNN Spike Operations:", int(snn_ops))

print("\nAverage ANN Latency:", ann_latency)
print("Average SNN Latency:", snn_latency)

print("\nEstimated ANN Energy:", ann_energy)
print("Estimated SNN Energy:", snn_energy)

print("\nEnergy Reduction Ratio:", ann_energy / snn_energy)

===== ANN vs SNN Comparison =====

ANN Operations: 117632
SNN Spike Operations: 265

Average ANN Latency: 5.1999568939208985e-05
Average SNN Latency: 0.004154521703720093

Estimated ANN Energy: 3.764224e-07
Estimated SNN Energy: 2.6500000000000002e-11

Energy Reduction Ratio: 14204.618867924528

In [262]:
reduction_ratio = ann_ops / snn_ops

print(" Computational Cost Comparison ")

print("ANN Operations per message:", ann_ops)
print("SNN Spike Operations per message:", snn_ops)

print("\nComputation Reduction Ratio:", reduction_ratio)

print("\nSNN performs approximately",
      round(reduction_ratio,2),
      "x fewer effective computations than ANN.")

 Computational Cost Comparison
ANN Operations per message: 117632
SNN Spike Operations per message: 265.0

Computation Reduction Ratio: 443.8943396226415

SNN performs approximately 443.89 x fewer effective computations than ANN.

### Importing file types for android studio

In [253]:
torch.save(model.state_dict(), "snn_spam_model.pth")

In [254]:
import joblib

joblib.dump(vectorizer, "vectorizer.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [255]:
import torch
import torch.nn as nn


# Same model architecture used in predict.py
class Net(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(917,128)
        self.fc2 = nn.Linear(128,2)

        self.beta = 0.9
        self.threshold = 1.0
        self.num_steps = 25

    def forward(self,x):

        batch_size = x.size(0)

        mem1 = torch.zeros(batch_size,128)
        mem2 = torch.zeros(batch_size,2)

        spk_sum = torch.zeros(batch_size,2)

        for _ in range(self.num_steps):

            mem1 = self.beta * mem1 + self.fc1(x)
            spk1 = (mem1 > self.threshold).float()
            mem1 = mem1 * (mem1 <= self.threshold)

            mem2 = self.beta * mem2 + self.fc2(spk1)
            spk2 = (mem2 > self.threshold).float()
            mem2 = mem2 * (mem2 <= self.threshold)

            spk_sum += spk2

        return spk_sum / self.num_steps


# Load model
model = Net()

state = torch.load("snn_spam_model.pth", map_location="cpu")
model.load_state_dict(state, strict=False)

model.eval()


# Convert to TorchScript
example = torch.rand(1,917)

traced_script_module = torch.jit.trace(model, example)

traced_script_module.save("spam_model.pt")

print("TorchScript model exported successfully")

TorchScript model exported successfully